### ISSUE TITLE
error for num_axes() <=4

### ISSUE THREAD

**Issue by gxdai** [rohitgirdhar/GenerativePredictableVoxels#2]
Hi, 

I tried to run "python src/testing/reconst.py", and I got the follow error.

Check failed: num_axes() <= 4 (5 vs. 4) Cannot use legacy accessors on Blobs with > 4 axes

Note, I tried both the caffe version you listed and the latest version. But I still get the same error.

Could you please help me solve the issue?

**Comment by rohitgirdhar** [comment]
Please refer to Issue https://github.com/rohitgirdhar/GenerativePredictableVoxels/issues/1
