### ISSUE TITLE
Output CSV with mesh points instead of image

### ISSUE THREAD

**Issue by roscopecoltran** [rohitgirdhar/GenerativePredictableVoxels#3]
Hi,

Hope you are all well !

Was wondering if it could be possible to output a csv file with the object points of object detected as wanted to try it with unity and use procedural meshes to visualize them in 3D. 

Would be awesome if you could help me or give a hint about how to do it with caffe as I have no "deep" experience in deep learning. :-)

Richard

**Comment by dfouhey** [comment]
The output is a 3D voxel grid, which you can transform into a mesh using standard 3D modeling tools (like marching cubes).
