### ISSUE TITLE
The link of Dropbox is invalid now

### ISSUE THREAD

**Issue by kealennieh** [rohitgirdhar/GenerativePredictableVoxels#6]
Hello, authors. I'm afraid that the link of Dropbox is invalid now. Is it convenient for you to check the link, or upload the required models into the models folder?  Many thanks!
By the way, is there any useful tool to transform CAD model into voxel grids? You mentioned the voxelizer in your paper, however I cannot find it. Can you give me a hand to post the link. Thanks a lot.

Best wishes.

**Comment by rohitgirdhar** [comment]
The link is still up and accessible
The voxelizer is here: http://www.patrickmin.com/binvox/

**Comment by kealennieh** [comment]
Thanks a lot ! I've found the voxelizer. BTW, your rendering images attached in your paper seem great. What kind of software do you use ? ShapeNet Viewer, or 3dmax ? 
 As you know, ShapeNet Viewer cannot simulate illumination variations. But 3dmax is hard to control the tracking to get the rendering images.  Therefore, I'm so curious about the software you used.  Could you tell me ? Thanks in advance!

**Comment by rohitgirdhar** [comment]
I used [blender](https://www.blender.org/), essentially from [Render For CNN](https://shapenet.cs.stanford.edu/projects/RenderForCNN/) code
