### ISSUE TITLE
Excuse me？ How can I train it？There is an issue about "No module named VoxelSnapshotLayer"

### ISSUE THREAD

**Issue by LouiValley** [rohitgirdhar/GenerativePredictableVoxels#7]
Excuse me？ How can I train it？There is an issue about "No module named VoxelSnapshotLayer"

**Comment by LouiValley** [comment]
Sorry to bother you again. When I run the train codes, there is an issue about "No module named VoxelSnapshotLayer" How can I solve it?  Do you upload this python layer named"VoxelSnapshotLayer"?

**Comment by rohitgirdhar** [comment]
The train_val.prototxt is released as a reference to our model architecture. The VoxelSnapshot layer is a custom python data loading layer.. unfortunately I haven't had the time to clean up and release that code. However the rest of the layers are all in-built caffe layers, so you would only need a data loader to work with it.
